name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B -q install
    - name: Store application artifact
      run: |
        mkdir staging
        cp app/target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - name: Store test report
      run: |
        mvn surefire-report:report-only
        mvn site -DgenerateReports=false
        mkdir test-report-app
        mkdir test-report-core
        mkdir test-report-data
        mkdir test-report-presenter
        cp -R app/target/site test-report-app
        cp -R core/target/site test-report-core
        cp -R data/target/site test-report-data
        cp -R presenter/target/site test-report-presenter
    - uses: actions/upload-artifact@v2
      with:
        name: Test report app
        path: test-report-app
    - uses: actions/upload-artifact@v2
      with:
        name: Test report core
        path: test-report-core
