name: Snyk Vulnerability Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Access to file
        run: git update-index --chmod=+x mvnw
        
      - name: Dependency tree
        run: ./mvnw dependency:tree -DoutputType=dot --file="pom.xml"
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
